/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Emilly
 */
public class Alterar extends javax.swing.JFrame {

    /**
     * Creates new form Alterar
     */
    String Nome;
    
    public Alterar() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/beberA.png")).getImage());
        try {
            FileReader arquivo = new FileReader("./bancodedados/usr/usuarioativo.txt");
            BufferedReader linha = new BufferedReader(arquivo);
            
            Nome = linha.readLine();
            jnome.setText(Nome);
            jsenha.setText(linha.readLine());
            jcpf.setText(linha.readLine());
            jdata.setText(linha.readLine());
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaverde = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jdata = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcpf = new javax.swing.JFormattedTextField();
        jsenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jnome = new javax.swing.JTextField();
        botcadastro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chafeteria Blima's");
        setResizable(false);
        getContentPane().setLayout(null);

        telaverde.setBackground(new java.awt.Color(39, 90, 56));
        telaverde.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALTERAR");
        telaverde.add(jLabel1);
        jLabel1.setBounds(90, 10, 116, 33);

        try {
            jdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jdata.setText("    /    /     ");
        jdata.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdataActionPerformed(evt);
            }
        });
        telaverde.add(jdata);
        jdata.setBounds(190, 180, 83, 20);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATA NASCIMENTO:");
        telaverde.add(jLabel2);
        jLabel2.setBounds(10, 180, 163, 19);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SENHA:");
        telaverde.add(jLabel3);
        jLabel3.setBounds(10, 100, 60, 19);

        try {
            jcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jcpf.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        telaverde.add(jcpf);
        jcpf.setBounds(80, 140, 130, 30);

        jsenha.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        telaverde.add(jsenha);
        jsenha.setBounds(80, 100, 130, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CPF:");
        telaverde.add(jLabel5);
        jLabel5.setBounds(10, 140, 50, 19);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOME:");
        telaverde.add(jLabel6);
        jLabel6.setBounds(10, 60, 60, 19);

        jnome.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        telaverde.add(jnome);
        jnome.setBounds(80, 60, 130, 30);

        botcadastro.setText("ALTERAR");
        botcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botcadastroActionPerformed(evt);
            }
        });
        telaverde.add(botcadastro);
        botcadastro.setBounds(100, 240, 90, 23);

        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        telaverde.add(jButton1);
        jButton1.setBounds(100, 270, 90, 23);

        getContentPane().add(telaverde);
        telaverde.setBounds(150, 50, 310, 390);

        fundo.setBackground(new java.awt.Color(255, 255, 255));
        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoplantas3.png"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 640, 440);

        setSize(new java.awt.Dimension(646, 463));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdataActionPerformed

    private void botcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botcadastroActionPerformed
        String nome, senha, cpf, data_nasc;

        nome = jnome.getText();
        senha = jsenha.getText();
        cpf = jcpf.getText();          
        data_nasc = jdata.getText();

        if("".equals(nome) || "".equals(senha) || "   .   .   -  ".equals(cpf) || "  /  /    ".equals(data_nasc)){ //verifica se os campos estão em branco
            JOptionPane.showMessageDialog(null, "Campo em branco! Preencha todos os campos.");
        }else{
            try {
                File arquivo2 = new File("./bancodedados/usr/" +Nome+ ".txt");
                arquivo2.delete();
                
                FileWriter arquivo = new FileWriter ("./bancodedados/usr/" + nome + ".txt", false); //escreve e instancia um objeto que criará um arquivo - false: reescrever o arquivo, caso seja falso
                PrintWriter escrever = new PrintWriter (arquivo); //objeto que vai ser escrito
                escrever.println(nome); //escreve as informações inseridas
                escrever.println(senha); //escreve as informações inseridas
                escrever.println(cpf); //escreve as informações inseridas
                escrever.println(data_nasc); //escreve as informações inseridas
                arquivo.flush(); //finalização do arquivo
                escrever.close(); //encerrar o objeto
                arquivo.close(); //encerrar o objeto
                JOptionPane.showMessageDialog(null, "Dados Atualizados!"); 
                jnome.setText(""); //limpar os campos ao finalizar o cadastro
                jsenha.setText("");
                jcpf.setText("");
                jdata.setText("");
                
                
                
                FileWriter arquivo3 = new FileWriter ("./bancodedados/usr/usuarioativo.txt", false); //escreve e instancia um objeto que criará um arquivo - false: reescrever o arquivo, caso seja falso
                PrintWriter escrever2 = new PrintWriter (arquivo3); //objeto que vai ser escrito
                escrever2.println(nome); //escreve as informações inseridas
                escrever2.println(senha); //escreve as informações inseridas
                escrever2.println(cpf); //escreve as informações inseridas
                escrever2.println(data_nasc);
                arquivo3.flush();
                escrever2.close();
                arquivo3.close(); 
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro no arquivo!");
            }
        }
    }//GEN-LAST:event_botcadastroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Conta().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alterar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botcadastro;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField jcpf;
    private javax.swing.JFormattedTextField jdata;
    private javax.swing.JTextField jnome;
    private javax.swing.JPasswordField jsenha;
    private javax.swing.JPanel telaverde;
    // End of variables declaration//GEN-END:variables
}
