/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author emi
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/beberA.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        painelverde = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        campouser = new javax.swing.JTextField();
        camposenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        painelfundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chafeteria Blima's");
        setResizable(false);
        getContentPane().setLayout(null);

        painelverde.setBackground(new java.awt.Color(39, 90, 56));

        login.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");

        user.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("USUÁRIO:");

        senha.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        senha.setForeground(new java.awt.Color(255, 255, 255));
        senha.setText("SENHA:");

        campouser.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        campouser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campouserActionPerformed(evt);
            }
        });

        camposenha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        camposenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camposenhaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setText("ENTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelverdeLayout = new javax.swing.GroupLayout(painelverde);
        painelverde.setLayout(painelverdeLayout);
        painelverdeLayout.setHorizontalGroup(
            painelverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelverdeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login)
                .addGap(102, 102, 102))
            .addGroup(painelverdeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user)
                    .addComponent(senha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(camposenha, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campouser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        painelverdeLayout.setVerticalGroup(
            painelverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelverdeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login)
                .addGap(15, 15, 15)
                .addGroup(painelverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user)
                    .addComponent(campouser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senha)
                    .addComponent(camposenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        getContentPane().add(painelverde);
        painelverde.setBounds(150, 50, 310, 360);

        painelfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoplantas3.png"))); // NOI18N
        getContentPane().add(painelfundo);
        painelfundo.setBounds(0, 0, 610, 400);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/casa.png"))); // NOI18N
        jMenu1.setText("HOME");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/eu-iria.png"))); // NOI18N
        jMenuItem1.setText("CADASTRO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("SAIR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(614, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void camposenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camposenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_camposenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{ //"bloco protegido" pois caso os comandos do bloco derem errado ele vai desviar pro catch
        String usuario = "";
        String senha = "";
        String arquivoUsuario, arquivoSenha, cpf, data;
        
        usuario = campouser.getText();
        senha = camposenha.getText();
        
        FileReader arquivo = new FileReader("./bancodedados/usr/" + usuario + ".txt"); //procurar e ler o arquivo com o nome do usuário
        BufferedReader linha = new BufferedReader(arquivo); //iniciando o objeto que lerá a linha
        
        arquivoUsuario = linha.readLine(); //ler a linha do usuário
        arquivoSenha = linha.readLine(); //ler a linha de senha
        
        cpf = linha.readLine();
        data = linha.readLine();
        
        linha.close();
        arquivo.close();
            
        if(arquivoUsuario.equalsIgnoreCase(usuario)&& arquivoSenha.equals(senha)){ //confere SE a senha e user digitado pelo usuário corresponde com o cadastro
            
            dispose();
            new Menu().setVisible(true);
            
            FileWriter arquivo3 = new FileWriter("./bancodedados/usr/usuarioativo.txt", false);
            PrintWriter escrever = new PrintWriter(arquivo3);
            
            escrever.println(usuario);
            escrever.println(senha);
            escrever.println(cpf);
            escrever.println(data);
            
            escrever.flush();
            escrever.close();
            arquivo3.close();
        }else{
            JOptionPane.showMessageDialog(null, "Error404");
        }
           
    } catch(IOException e){ //resposta para possivel erro
            JOptionPane.showMessageDialog(null, "Esta conta não existe, tente novamente com outra, ou cadastra-se!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new TelaCad().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
        JOptionPane.showMessageDialog(null, "Volte Sempre!");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void campouserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campouserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campouserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField camposenha;
    private javax.swing.JTextField campouser;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel login;
    private javax.swing.JLabel painelfundo;
    private javax.swing.JPanel painelverde;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

    private void PrintWriter(FileWriter arquivo3) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
