/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Emilly
 */
public class Pesquisa extends javax.swing.JFrame {

    /**
     * Creates new form Pesquisa
     */
    public Pesquisa() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/beberA.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPesq = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        jLabel2.setText("Pesquisar produto: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 20, 258, 43);

        jPesq.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesqActionPerformed(evt);
            }
        });
        jPanel1.add(jPesq);
        jPesq.setBounds(130, 60, 216, 32);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search e.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 60, 73, 30);

        jPanel2.setBackground(new java.awt.Color(39, 90, 56));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nossos Produtos:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(140, 0, 230, 30);

        jTextArea1.setBackground(new java.awt.Color(39, 90, 56));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Chás:\t                      Código:\nAlecrim\t\t#1\nBoldo\t\t#1\nCamomila\t\t#1\nChá verde\t\t#1\nErva doce\t\t#1\nEucalipto\t\t#1\nGengibre\t\t#2\nMaracujá\t\t#2\nQuebra-pedra  \t#2\nCapim lima\t\t#2\nCidreira\t\t#2\nGuaraná\t\t#2\nHortelã\t\t#3\nHibísco\t\t#3\nMulungú \t\t#3\nOrégano\t\t#3\nGergelim\t\t#3\nCanela de velho\t#3");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 20, 480, 220);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 130, 480, 270);

        jProgressBar1.setBackground(new java.awt.Color(39, 90, 56));
        jProgressBar1.setForeground(new java.awt.Color(0, 204, 204));
        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(130, 100, 216, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 40, 480, 420);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoplantas3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -10, 620, 460);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/casa.png"))); // NOI18N
        jMenu1.setText("HOME");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/do-utilizador.png"))); // NOI18N
        jMenuItem6.setText("CONTA");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem1.setText("SAIR DA CONTA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/preco.png"))); // NOI18N
        jMenu2.setText("PRODUTOS");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/conta.png"))); // NOI18N
        jMenuItem4.setText("NOTA FISCAL");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bill.png"))); // NOI18N
        jMenuItem2.setText("PAGAMENTO");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed1(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(617, 477));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPesqActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Pesq;
        
        Pesq = jPesq.getText().toLowerCase();
        
        new Thread(){
            public void run(){
                for(int i = 0; i <= 100; i++){
                    try {
                        sleep(50);
                        jProgressBar1.setValue(i);
                        
                    } 
                    catch (InterruptedException ex) {
                        
                    }
                } 
                
        switch(Pesq){
            
        case "#1": dispose();
                new Produtos_p0().setVisible(true);
                break;
        
        case "#3": dispose();
                new Produtos_p2().setVisible(true);
                break;
                
        case "#2": dispose();
                new Produtos_p1().setVisible(true);
                break;
 
        default:
            JOptionPane.showMessageDialog(null, "Produto não encontrado! \nTente novamente");
            break;
        }
            }
        }.start();
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Conta().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", false);
            FileWriter arquivo4 = new FileWriter("./bancodedados/lista.txt", false);
            FileWriter arquivo5 = new FileWriter("./bancodedados/quant.txt", false);
            FileWriter arquivo6 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever = new PrintWriter(arquivo6);
            escrever.println("0");
            
            arquivo3.close();
            arquivo4.close();
            arquivo5.close();
            arquivo6.close();
            
        } catch (Exception e) {
        }
        dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            new NotaFiscal().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Pesquisa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed1
        // TODO add your handling code here:
        dispose();
        new Pagamento().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed1

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPesq;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
