/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author emi
 */
public class Produtos_p0 extends javax.swing.JFrame {

    /**
     * Creates new form Produtos_p0
     */
    public Produtos_p0() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/beberA.png")).getImage());
        JOptionPane.showMessageDialog(null, "Para confirmar o pedido clique na imagem do respectivo produto\n"
                + "(Faça isso com os produtos escolhidos)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ale = new javax.swing.JSpinner();
        bol = new javax.swing.JSpinner();
        camo = new javax.swing.JSpinner();
        cha = new javax.swing.JSpinner();
        erva = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        eu = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        eucalipto = new javax.swing.JButton();
        ervadoce = new javax.swing.JButton();
        camomila = new javax.swing.JButton();
        boldo = new javax.swing.JButton();
        alecrim = new javax.swing.JButton();
        chaverde = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jLabel17.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel17.setText("R$ 3,00");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chaveteria Blima's");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("ALECRIM");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(32, 152, 67, 18);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setText("CAMOMILA");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 150, 80, 30);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(518, 152, 0, 0);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setText("BOLDO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 150, 51, 20);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setText("CHÁ VERDE");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 357, 86, 20);

        ale.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jPanel1.add(ale);
        ale.setBounds(109, 152, 39, 30);

        bol.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        bol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(bol);
        bol.setBounds(261, 152, 39, 30);

        camo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jPanel1.add(camo);
        camo.setBounds(470, 160, 39, 30);

        cha.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jPanel1.add(cha);
        cha.setBounds(120, 360, 39, 30);

        erva.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jPanel1.add(erva);
        erva.setBounds(300, 360, 39, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setText("ERVA DOCE");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 348, 86, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setText("EUCALIPTO");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 348, 87, 30);

        eu.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jPanel1.add(eu);
        eu.setBounds(460, 360, 39, 30);

        jLabel11.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel11.setText("R$ 3,00");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 160, 52, 20);

        jLabel12.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel12.setText("R$ 3,00");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(200, 370, 50, 15);

        jLabel13.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel13.setText("R$ 3,00");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(370, 165, 54, 20);

        jLabel14.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel14.setText("R$ 3,00");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(370, 370, 53, 15);

        jLabel15.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel15.setText("R$ 3,00");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 370, 50, 20);

        jLabel16.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel16.setText("R$ 3,00");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(200, 160, 50, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(510, 370, 40, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/prod1.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 180, 550, 170);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/prod1.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, -10, 550, 180);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 560, 450);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoplantas3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 630, 470);

        eucalipto.setText("jButton1");
        eucalipto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eucaliptoActionPerformed(evt);
            }
        });
        getContentPane().add(eucalipto);
        eucalipto.setBounds(390, 220, 150, 140);

        ervadoce.setText("jButton1");
        ervadoce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ervadoceActionPerformed(evt);
            }
        });
        getContentPane().add(ervadoce);
        ervadoce.setBounds(220, 220, 150, 150);

        camomila.setText("camomila");
        camomila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camomilaActionPerformed(evt);
            }
        });
        getContentPane().add(camomila);
        camomila.setBounds(390, 20, 150, 150);

        boldo.setText("jButton1");
        boldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boldoActionPerformed(evt);
            }
        });
        getContentPane().add(boldo);
        boldo.setBounds(220, 20, 150, 150);

        alecrim.setText("alecrim");
        alecrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alecrimActionPerformed(evt);
            }
        });
        getContentPane().add(alecrim);
        alecrim.setBounds(50, 20, 150, 150);

        chaverde.setText("jButton2");
        chaverde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chaverdeActionPerformed(evt);
            }
        });
        getContentPane().add(chaverde);
        chaverde.setBounds(43, 223, 160, 150);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/casa.png"))); // NOI18N
        jMenu1.setText("HOME");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/do-utilizador.png"))); // NOI18N
        jMenuItem6.setText("CONTA");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cardapio.png"))); // NOI18N
        jMenuItem5.setText("MENU");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem1.setText("SAIR DA CONTA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/preco.png"))); // NOI18N
        jMenu2.setText("PRODUTOS");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search e.png"))); // NOI18N
        jMenuItem3.setText("PESQUISAR PRODUTO");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/conta.png"))); // NOI18N
        jMenuItem4.setText("NOTA FISCAL");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bill.png"))); // NOI18N
        jMenuItem2.setText("PAGAMENTO");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(617, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alecrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alecrimActionPerformed
        // TODO add your handling code here:
            int quant;
            double valor;
            
            valor = 3.00;
            
            quant = (int) ale.getValue(); //conversão de String do botão para int
            
            valor *= quant; //multiplicar a quantidade pelo valor, atribuindo o resultado a variavel valor
            
            try {
            FileWriter arquivo = new FileWriter("./bancodedados/lista.txt", true);
            PrintWriter escrever = new PrintWriter(arquivo);
            escrever.println("Alecrim");
            arquivo.flush();
            escrever.close();
            arquivo.close();
            
            FileWriter arquivo2 = new FileWriter("./bancodedados/quant.txt", true);
            PrintWriter escrever2 = new PrintWriter(arquivo2);
            escrever2.println(quant);
            arquivo2.flush();
            escrever2.close();
            arquivo2.close();
            
            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", true);
            PrintWriter escrever3 = new PrintWriter(arquivo3);
            escrever3.println(valor);
            arquivo3.flush();
            escrever3.close();
            arquivo3.close();
            
            FileReader arquivo4 = new FileReader("./bancodedados/NumProd.txt");
            BufferedReader linha = new BufferedReader(arquivo4);
            
            String rec = linha.readLine();
            int n = Integer.parseInt(rec);
            
            linha.close();
            arquivo4.close();
            
            n+=1; //adicionando + 1 na lista
            
            FileWriter arquivo5 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever5 = new PrintWriter(arquivo5);
            escrever5.println(n);
            arquivo5.flush();
            escrever5.close();
            arquivo5.close();
            
            JOptionPane.showMessageDialog(null, "Compra adicionada no carrinho!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro");
        }
            
    }//GEN-LAST:event_alecrimActionPerformed

    private void boldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boldoActionPerformed
        // TODO add your handling code here:
            int quant;
            double valor;
            
            valor = 3.00;
            
            quant = (int) bol.getValue();
            
            valor *= quant;
            
            try {
            FileWriter arquivo = new FileWriter("./bancodedados/lista.txt", true);
            PrintWriter escrever = new PrintWriter(arquivo);
            escrever.println("Boldo");
            arquivo.flush();
            escrever.close();
            arquivo.close();
            
            FileWriter arquivo2 = new FileWriter("./bancodedados/quant.txt", true);
            PrintWriter escrever2 = new PrintWriter(arquivo2);
            escrever2.println(quant);
            arquivo2.flush();
            escrever2.close();
            arquivo2.close();
            
            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", true);
            PrintWriter escrever3 = new PrintWriter(arquivo3);
            escrever3.println(valor);
            arquivo3.flush();
            escrever3.close();
            arquivo3.close();
            
            FileReader arquivo4 = new FileReader("./bancodedados/NumProd.txt");
            BufferedReader linha = new BufferedReader(arquivo4);
            
            String rec = linha.readLine();
            int n = Integer.parseInt(rec);
            
            linha.close();
            arquivo4.close();
            
            n+=1; //adicionando + 1 na lista
            
            FileWriter arquivo5 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever5 = new PrintWriter(arquivo5);
            escrever5.println(n);
            arquivo5.flush();
            escrever5.close();
            arquivo5.close();
            
            JOptionPane.showMessageDialog(null, "Compra adicionada no carrinho!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro");
        }                
    }//GEN-LAST:event_boldoActionPerformed

    private void camomilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camomilaActionPerformed
        // TODO add your handling code here:
            int quant;
            double valor;
            
            valor = 3.00;
            
            quant = (int) camo.getValue();
            
            valor *= quant;
            
            try {
            FileWriter arquivo = new FileWriter("./bancodedados/lista.txt", true);
            PrintWriter escrever = new PrintWriter(arquivo);
            escrever.println("Camomila");
            arquivo.flush();
            escrever.close();
            arquivo.close();
            
            FileWriter arquivo2 = new FileWriter("./bancodedados/quant.txt", true);
            PrintWriter escrever2 = new PrintWriter(arquivo2);
            escrever2.println(quant);
            arquivo2.flush();
            escrever2.close();
            arquivo2.close();
            
            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", true);
            PrintWriter escrever3 = new PrintWriter(arquivo3);
            escrever3.println(valor);
            arquivo3.flush();
            escrever3.close();
            arquivo3.close();
            
            FileReader arquivo4 = new FileReader("./bancodedados/NumProd.txt");
            BufferedReader linha = new BufferedReader(arquivo4);
            
            String rec = linha.readLine();
            int n = Integer.parseInt(rec);
            
            linha.close();
            arquivo4.close();
            
            n+=1; //adicionando + 1 na lista
            
            FileWriter arquivo5 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever5 = new PrintWriter(arquivo5);
            escrever5.println(n);
            arquivo5.flush();
            escrever5.close();
            arquivo5.close();
            
            JOptionPane.showMessageDialog(null, "Compra adicionada no carrinho!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro");        
    }                
    }//GEN-LAST:event_camomilaActionPerformed

    private void chaverdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chaverdeActionPerformed
        // TODO add your handling code here:
            int quant;
            double valor;
            
            valor = 3.00;
            
            quant = (int) cha.getValue();
            
            valor *= quant;
            
            try {
            FileWriter arquivo = new FileWriter("./bancodedados/lista.txt", true);
            PrintWriter escrever = new PrintWriter(arquivo);
            escrever.println("Chá verde");
            arquivo.flush();
            escrever.close();
            arquivo.close();
            
            FileWriter arquivo2 = new FileWriter("./bancodedados/quant.txt", true);
            PrintWriter escrever2 = new PrintWriter(arquivo2);
            escrever2.println(quant);
            arquivo2.flush();
            escrever2.close();
            arquivo2.close();
            
            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", true);
            PrintWriter escrever3 = new PrintWriter(arquivo3);
            escrever3.println(valor);
            arquivo3.flush();
            escrever3.close();
            arquivo3.close();
            
            FileReader arquivo4 = new FileReader("./bancodedados/NumProd.txt");
            BufferedReader linha = new BufferedReader(arquivo4);
            
            String rec = linha.readLine();
            int n = Integer.parseInt(rec);
            
            linha.close();
            arquivo4.close();
            
            n+=1; //adicionando + 1 na lista
            
            FileWriter arquivo5 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever5 = new PrintWriter(arquivo5);
            escrever5.println(n);
            arquivo5.flush();
            escrever5.close();
            arquivo5.close();
            
            JOptionPane.showMessageDialog(null, "Compra adicionada no carrinho!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro");
        }                
    }//GEN-LAST:event_chaverdeActionPerformed

    private void ervadoceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ervadoceActionPerformed
        // TODO add your handling code here:
            int quant;
            double valor;
            
            valor = 3.00;
            
            quant = (int) erva.getValue();
            
            valor *= quant;
            
            try {
            FileWriter arquivo = new FileWriter("./bancodedados/lista.txt", true);
            PrintWriter escrever = new PrintWriter(arquivo);
            escrever.println("Erva Doce");
            arquivo.flush();
            escrever.close();
            arquivo.close();
            
            FileWriter arquivo2 = new FileWriter("./bancodedados/quant.txt", true);
            PrintWriter escrever2 = new PrintWriter(arquivo2);
            escrever2.println(quant);
            arquivo2.flush();
            escrever2.close();
            arquivo2.close();
            
            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", true);
            PrintWriter escrever3 = new PrintWriter(arquivo3);
            escrever3.println(valor);
            arquivo3.flush();
            escrever3.close();
            arquivo3.close();
            
            FileReader arquivo4 = new FileReader("./bancodedados/NumProd.txt");
            BufferedReader linha = new BufferedReader(arquivo4);
            
            String rec = linha.readLine();
            int n = Integer.parseInt(rec);
            
            linha.close();
            arquivo4.close();
            
            n+=1; //adicionando + 1 na lista
            
            FileWriter arquivo5 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever5 = new PrintWriter(arquivo5);
            escrever5.println(n);
            arquivo5.flush();
            escrever5.close();
            arquivo5.close();
            
            JOptionPane.showMessageDialog(null, "Compra adicionada no carrinho!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_ervadoceActionPerformed

    private void eucaliptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eucaliptoActionPerformed
        // TODO add your handling code here:
            int quant;
            double valor;
            
            valor = 3.00;
            
            quant = (int) eu.getValue();
            
            valor *= quant;
            
            try {
            FileWriter arquivo = new FileWriter("./bancodedados/lista.txt", true);
            PrintWriter escrever = new PrintWriter(arquivo);
            escrever.println("Eucalipto");
            arquivo.flush();
            escrever.close();
            arquivo.close();
            
            FileWriter arquivo2 = new FileWriter("./bancodedados/quant.txt", true);
            PrintWriter escrever2 = new PrintWriter(arquivo2);
            escrever2.println(quant);
            arquivo2.flush();
            escrever2.close();
            arquivo2.close();
            
            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", true);
            PrintWriter escrever3 = new PrintWriter(arquivo3);
            escrever3.println(valor);
            arquivo3.flush();
            escrever3.close();
            arquivo3.close();
            
            FileReader arquivo4 = new FileReader("./bancodedados/NumProd.txt");
            BufferedReader linha = new BufferedReader(arquivo4);
            
            String rec = linha.readLine();
            int n = Integer.parseInt(rec);
            
            linha.close();
            arquivo4.close();
            
            n+=1; //adicionando + 1 na lista
            
            FileWriter arquivo5 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever5 = new PrintWriter(arquivo5);
            escrever5.println(n);
            arquivo5.flush();
            escrever5.close();
            arquivo5.close();
            
            JOptionPane.showMessageDialog(null, "Compra adicionada no carrinho!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_eucaliptoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Pesquisa().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            new NotaFiscal().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Produtos_p0.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", false);
            FileWriter arquivo4 = new FileWriter("./bancodedados/lista.txt", false);
            FileWriter arquivo5 = new FileWriter("./bancodedados/quant.txt", false);
            FileWriter arquivo6 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever = new PrintWriter(arquivo6);
            escrever.println("0");
            
            arquivo3.close();
            arquivo4.close();
            arquivo5.close();
            arquivo6.close();
            
        } catch (Exception e) {
        }
        dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Pagamento().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Conta().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Produtos_p1().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos_p0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos_p0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos_p0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos_p0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos_p0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ale;
    private javax.swing.JButton alecrim;
    private javax.swing.JSpinner bol;
    private javax.swing.JButton boldo;
    private javax.swing.JSpinner camo;
    private javax.swing.JButton camomila;
    private javax.swing.JSpinner cha;
    private javax.swing.JButton chaverde;
    private javax.swing.JSpinner erva;
    private javax.swing.JButton ervadoce;
    private javax.swing.JSpinner eu;
    private javax.swing.JButton eucalipto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
