/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Emilly
 */
public class Produtos_p1 extends javax.swing.JFrame {

    /**
     * Creates new form Produtos_p1
     */
    public Produtos_p1() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/beberA.png")).getImage());
        JOptionPane.showMessageDialog(null, "Para confirmar o pedido clique na imagem do respectivo produto\n"
                + "(Faça isso com os produtos escolhidos)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gen = new javax.swing.JSpinner();
        mara = new javax.swing.JSpinner();
        queb = new javax.swing.JSpinner();
        cap = new javax.swing.JSpinner();
        cid = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gua = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cidreira = new javax.swing.JButton();
        capim = new javax.swing.JButton();
        guarana = new javax.swing.JButton();
        quebra = new javax.swing.JButton();
        maracuja = new javax.swing.JButton();
        gengibre = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chafeteria Blima's");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("GENGIBRE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 160, 90, 18);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setText("QUEBRA-PEDRA");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 160, 140, 18);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(518, 152, 0, 0);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setText("MARACUJÁ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 160, 110, 20);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setText("CAPIM LIMA");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 350, 110, 60);

        gen.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jPanel1.add(gen);
        gen.setBounds(140, 160, 39, 30);

        mara.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        mara.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(mara);
        mara.setBounds(310, 160, 39, 30);

        queb.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jPanel1.add(queb);
        queb.setBounds(490, 160, 39, 30);

        cap.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jPanel1.add(cap);
        cap.setBounds(140, 370, 39, 30);

        cid.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jPanel1.add(cid);
        cid.setBounds(310, 370, 39, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setText("CIDREIRA");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 348, 72, 60);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setText("GUARANÁ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 360, 73, 40);

        gua.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jPanel1.add(gua);
        gua.setBounds(460, 370, 39, 30);

        jLabel11.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel11.setText("R$ 3,00");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 170, 52, 20);

        jLabel12.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel12.setText("R$ 3,00");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(200, 370, 50, 40);

        jLabel13.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel13.setText("R$ 3,00");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(370, 170, 60, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/prod1.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 180, 530, 200);

        jLabel14.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel14.setText("R$ 3,00");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(370, 370, 53, 40);

        jLabel15.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel15.setText("R$ 3,00");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 370, 50, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/prod1.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, -20, 530, 210);

        jLabel16.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel16.setText("R$ 3,00");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(200, 170, 50, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(520, 340, 40, 40);

        cidreira.setText("jButton1");
        cidreira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidreiraActionPerformed(evt);
            }
        });
        jPanel1.add(cidreira);
        cidreira.setBounds(200, 200, 150, 150);

        capim.setBackground(new java.awt.Color(255, 255, 255));
        capim.setText("jButton2");
        capim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capimActionPerformed(evt);
            }
        });
        jPanel1.add(capim);
        capim.setBounds(20, 200, 160, 150);

        guarana.setText("jButton1");
        guarana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guaranaActionPerformed(evt);
            }
        });
        jPanel1.add(guarana);
        guarana.setBounds(370, 200, 150, 150);

        quebra.setText("quebra");
        quebra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quebraActionPerformed(evt);
            }
        });
        jPanel1.add(quebra);
        quebra.setBounds(370, 10, 150, 150);

        maracuja.setText("maracuja");
        maracuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maracujaActionPerformed(evt);
            }
        });
        jPanel1.add(maracuja);
        maracuja.setBounds(200, 10, 150, 150);

        gengibre.setText("gengibre");
        gengibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gengibreActionPerformed(evt);
            }
        });
        jPanel1.add(gengibre);
        gengibre.setBounds(20, 10, 160, 150);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 380, 40, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 560, 450);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoplantas3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 630, 470);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/casa.png"))); // NOI18N
        jMenu1.setText("HOME");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/do-utilizador.png"))); // NOI18N
        jMenuItem6.setText("CONTA");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cardapio.png"))); // NOI18N
        jMenuItem5.setText("MENU");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem1.setText("SAIR DA CONTA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/preco.png"))); // NOI18N
        jMenu2.setText("PRODUTOS");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search e.png"))); // NOI18N
        jMenuItem3.setText("PESQUISAR PRODUTO");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/conta.png"))); // NOI18N
        jMenuItem4.setText("NOTA FISCAL");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/bill.png"))); // NOI18N
        jMenuItem2.setText("PAGAMENTO");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(617, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guaranaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guaranaActionPerformed
        // TODO add your handling code here:
        int quant;
        double valor;

        valor = 3.00;

        quant = (int) gua.getValue();

        valor *= quant;

        try {
            FileWriter arquivo = new FileWriter("./bancodedados/lista.txt", true);
            PrintWriter escrever = new PrintWriter(arquivo);
            escrever.println("Guaraná");
            arquivo.flush();
            escrever.close();
            arquivo.close();

            FileWriter arquivo2 = new FileWriter("./bancodedados/quant.txt", true);
            PrintWriter escrever2 = new PrintWriter(arquivo2);
            escrever2.println(quant);
            arquivo2.flush();
            escrever2.close();
            arquivo2.close();

            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", true);
            PrintWriter escrever3 = new PrintWriter(arquivo3);
            escrever3.println(valor);
            arquivo3.flush();
            escrever3.close();
            arquivo3.close();

            FileReader arquivo4 = new FileReader("./bancodedados/NumProd.txt");
            BufferedReader linha = new BufferedReader(arquivo4);

            String rec = linha.readLine();
            int n = Integer.parseInt(rec);

            linha.close();
            arquivo4.close();

            n+=1; //adicionando + 1 na lista

            FileWriter arquivo5 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever5 = new PrintWriter(arquivo5);
            escrever5.println(n);
            arquivo5.flush();
            escrever5.close();
            arquivo5.close();

            JOptionPane.showMessageDialog(null, "Compra adicionada no carrinho!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_guaranaActionPerformed

    private void cidreiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidreiraActionPerformed
        // TODO add your handling code here:
        int quant;
        double valor;

        valor = 3.00;

        quant = (int) cid.getValue();

        valor *= quant;

        try {
            FileWriter arquivo = new FileWriter("./bancodedados/lista.txt", true);
            PrintWriter escrever = new PrintWriter(arquivo);
            escrever.println("Cidreira");
            arquivo.flush();
            escrever.close();
            arquivo.close();

            FileWriter arquivo2 = new FileWriter("./bancodedados/quant.txt", true);
            PrintWriter escrever2 = new PrintWriter(arquivo2);
            escrever2.println(quant);
            arquivo2.flush();
            escrever2.close();
            arquivo2.close();

            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", true);
            PrintWriter escrever3 = new PrintWriter(arquivo3);
            escrever3.println(valor);
            arquivo3.flush();
            escrever3.close();
            arquivo3.close();

            FileReader arquivo4 = new FileReader("./bancodedados/NumProd.txt");
            BufferedReader linha = new BufferedReader(arquivo4);

            String rec = linha.readLine();
            int n = Integer.parseInt(rec);

            linha.close();
            arquivo4.close();

            n+=1; //adicionando + 1 na lista

            FileWriter arquivo5 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever5 = new PrintWriter(arquivo5);
            escrever5.println(n);
            arquivo5.flush();
            escrever5.close();
            arquivo5.close();

            JOptionPane.showMessageDialog(null, "Compra adicionada no carrinho!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_cidreiraActionPerformed

    private void quebraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quebraActionPerformed
        // TODO add your handling code here:
        int quant;
        double valor;

        valor = 3.00;

        quant = (int) queb.getValue();

        valor *= quant;

        try {
            FileWriter arquivo = new FileWriter("./bancodedados/lista.txt", true);
            PrintWriter escrever = new PrintWriter(arquivo);
            escrever.println("Quebra-pedra");
            arquivo.flush();
            escrever.close();
            arquivo.close();

            FileWriter arquivo2 = new FileWriter("./bancodedados/quant.txt", true);
            PrintWriter escrever2 = new PrintWriter(arquivo2);
            escrever2.println(quant);
            arquivo2.flush();
            escrever2.close();
            arquivo2.close();

            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", true);
            PrintWriter escrever3 = new PrintWriter(arquivo3);
            escrever3.println(valor);
            arquivo3.flush();
            escrever3.close();
            arquivo3.close();

            FileReader arquivo4 = new FileReader("./bancodedados/NumProd.txt");
            BufferedReader linha = new BufferedReader(arquivo4);

            String rec = linha.readLine();
            int n = Integer.parseInt(rec);

            linha.close();
            arquivo4.close();

            n+=1; //adicionando + 1 na lista

            FileWriter arquivo5 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever5 = new PrintWriter(arquivo5);
            escrever5.println(n);
            arquivo5.flush();
            escrever5.close();
            arquivo5.close();

            JOptionPane.showMessageDialog(null, "Compra adicionada no carrinho!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_quebraActionPerformed

    private void maracujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maracujaActionPerformed
        // TODO add your handling code here:
        int quant;
        double valor;

        valor = 3.00;

        quant = (int) mara.getValue();

        valor *= quant;

        try {
            FileWriter arquivo = new FileWriter("./bancodedados/lista.txt", true);
            PrintWriter escrever = new PrintWriter(arquivo);
            escrever.println("Maracujá");
            arquivo.flush();
            escrever.close();
            arquivo.close();

            FileWriter arquivo2 = new FileWriter("./bancodedados/quant.txt", true);
            PrintWriter escrever2 = new PrintWriter(arquivo2);
            escrever2.println(quant);
            arquivo2.flush();
            escrever2.close();
            arquivo2.close();

            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", true);
            PrintWriter escrever3 = new PrintWriter(arquivo3);
            escrever3.println(valor);
            arquivo3.flush();
            escrever3.close();
            arquivo3.close();

            FileReader arquivo4 = new FileReader("./bancodedados/NumProd.txt");
            BufferedReader linha = new BufferedReader(arquivo4);

            String rec = linha.readLine();
            int n = Integer.parseInt(rec);

            linha.close();
            arquivo4.close();

            n+=1; //adicionando + 1 na lista

            FileWriter arquivo5 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever5 = new PrintWriter(arquivo5);
            escrever5.println(n);
            arquivo5.flush();
            escrever5.close();
            arquivo5.close();

            JOptionPane.showMessageDialog(null, "Compra adicionada no carrinho!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_maracujaActionPerformed

    private void gengibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gengibreActionPerformed
        // TODO add your handling code here:
        int quant;
        double valor;

        valor = 3.00;

        quant = (int) gen.getValue(); //conversão de String do botão para int

        valor *= quant; //multiplicar a quantidade pelo valor, atribuindo o resultado a variavel valor

        try {
            FileWriter arquivo = new FileWriter("./bancodedados/lista.txt", true);
            PrintWriter escrever = new PrintWriter(arquivo);
            escrever.println("Gengibre");
            arquivo.flush();
            escrever.close();
            arquivo.close();

            FileWriter arquivo2 = new FileWriter("./bancodedados/quant.txt", true);
            PrintWriter escrever2 = new PrintWriter(arquivo2);
            escrever2.println(quant);
            arquivo2.flush();
            escrever2.close();
            arquivo2.close();

            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", true);
            PrintWriter escrever3 = new PrintWriter(arquivo3);
            escrever3.println(valor);
            arquivo3.flush();
            escrever3.close();
            arquivo3.close();

            FileReader arquivo4 = new FileReader("./bancodedados/NumProd.txt");
            BufferedReader linha = new BufferedReader(arquivo4);

            String rec = linha.readLine();
            int n = Integer.parseInt(rec);

            linha.close();
            arquivo4.close();

            n+=1; //adicionando + 1 na lista

            FileWriter arquivo5 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever5 = new PrintWriter(arquivo5);
            escrever5.println(n);
            arquivo5.flush();
            escrever5.close();
            arquivo5.close();

            JOptionPane.showMessageDialog(null, "Compra adicionada no carrinho!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro");
        }

    }//GEN-LAST:event_gengibreActionPerformed

    private void capimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capimActionPerformed
        // TODO add your handling code here:
        int quant;
        double valor;

        valor = 3.00;

        quant = (int) cap.getValue();

        valor *= quant;

        try {
            FileWriter arquivo = new FileWriter("./bancodedados/lista.txt", true);
            PrintWriter escrever = new PrintWriter(arquivo);
            escrever.println("Capim Lima");
            arquivo.flush();
            escrever.close();
            arquivo.close();

            FileWriter arquivo2 = new FileWriter("./bancodedados/quant.txt", true);
            PrintWriter escrever2 = new PrintWriter(arquivo2);
            escrever2.println(quant);
            arquivo2.flush();
            escrever2.close();
            arquivo2.close();

            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", true);
            PrintWriter escrever3 = new PrintWriter(arquivo3);
            escrever3.println(valor);
            arquivo3.flush();
            escrever3.close();
            arquivo3.close();

            FileReader arquivo4 = new FileReader("./bancodedados/NumProd.txt");
            BufferedReader linha = new BufferedReader(arquivo4);

            String rec = linha.readLine();
            int n = Integer.parseInt(rec);

            linha.close();
            arquivo4.close();

            n+=1; //adicionando + 1 na lista

            FileWriter arquivo5 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever5 = new PrintWriter(arquivo5);
            escrever5.println(n);
            arquivo5.flush();
            escrever5.close();
            arquivo5.close();

            JOptionPane.showMessageDialog(null, "Compra adicionada no carrinho!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_capimActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Conta().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            FileWriter arquivo3 = new FileWriter("./bancodedados/valor.txt", false);
            FileWriter arquivo4 = new FileWriter("./bancodedados/lista.txt", false);
            FileWriter arquivo5 = new FileWriter("./bancodedados/quant.txt", false);
            FileWriter arquivo6 = new FileWriter("./bancodedados/NumProd.txt", false);
            PrintWriter escrever = new PrintWriter(arquivo6);
            escrever.println("0");
            
            arquivo3.close();
            arquivo4.close();
            arquivo5.close();
            arquivo6.close();
            
        } catch (Exception e) {
        }
        dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Pesquisa().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            new NotaFiscal().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Produtos_p0.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Pagamento().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Produtos_p2().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Produtos_p0().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtos_p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtos_p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtos_p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtos_p1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produtos_p1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cap;
    private javax.swing.JButton capim;
    private javax.swing.JSpinner cid;
    private javax.swing.JButton cidreira;
    private javax.swing.JSpinner gen;
    private javax.swing.JButton gengibre;
    private javax.swing.JSpinner gua;
    private javax.swing.JButton guarana;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner mara;
    private javax.swing.JButton maracuja;
    private javax.swing.JSpinner queb;
    private javax.swing.JButton quebra;
    // End of variables declaration//GEN-END:variables
}
